version: "3"
services:
  web_flask:
    build:
      context: .
      args:
        project_directory: "/projects/"
    ports:
      - "5000:5000"
    volumes:
      - "./src:/projects"
    env_file:
      - ./src/db.env
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    tty: true
    command: "flask run --host 0.0.0.0 --port 5000"
